apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-go
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: telegram-bot-go
  template:
    metadata:
      labels:
        app: telegram-bot-go
    spec:
      containers:
        - name: bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
